Ticket\Entity\TicketPriority:
    type: entity
    table: ticket_priority
    repositoryClass: Ticket\Repository\TicketPriorityRepository
    indexes:
        deleted:
            columns: [deleted]
    fields:
        id:
            type: smallint
            id: true
            generator:
                strategy: AUTO
        priorityName:
            type: string
            length: '30'
            column: priority_name
        deleted:
            type: boolean
            options:
              default: '0'
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
        deletedAt:
            type: datetime
            column: deleted_at
            nullable: true
    lifecycleCallbacks: {  }
