Ticket\Entity\TicketCategory:
    type: entity
    table: ticket_category
    repositoryClass: Ticket\Repository\TicketCategoryRepository
    indexes:
        deleted:
            columns: [deleted]
    fields:
        id:
            type: smallint
            id: true
            generator:
                strategy: AUTO
        categoryName:
            type: string
            length: '60'
            column: category_name
        deleted:
            type: boolean
            options:
              default: '0'
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
        deletedAt:
            type: datetime
            column: deleted_at
            nullable: true
    lifecycleCallbacks: {  }
